version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: weather_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: weather_app
      MYSQL_ROOT_PASSWORD: Gangatharan@2004
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:


  


